<?php
/**
 * @file
 * murder_scenario_node_type.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function murder_scenario_node_type_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_difficulty'
  $field_bases['field_difficulty'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_difficulty',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'child' => 'Child\'s play',
        'easy' => 'Easy',
        'normal' => 'Normal',
        'cop' => 'Policeman',
        'columbo' => 'Columbo',
        'sherlock' => 'Sherlock Holmes',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_duration'
  $field_bases['field_duration'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_duration',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'hms_field',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'hms_field',
  );

  // Exported field_base: 'field_mark'
  $field_bases['field_mark'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_mark',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_player_number'
  $field_bases['field_player_number'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_player_number',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'number_integer',
  );

  return $field_bases;
}
